all:
	# WB 2016
	@echo 'WB 2016 Constituency'
	@python3 west-bengal-2016-assembly.py

	@echo 'WB 2016 Winners'
	@python3 west-bengal-2016-winners.py

	@echo 'WB 2016 Winner Expenses'
	@python3 west-bengal-2016-winner-expenses.py

	@echo 'WB 2016 Constituency Page'
	@node west-bengal-2016-constituency-page-specific.js
	@python3 west-bengal-2016-constituency-page-specific.py

	# WB 2011
	@echo 'WB 2011 Constituency'
	@python3 west-bengal-2011-assembly.py

	@echo 'WB 2011 Winners'
	@python3 west-bengal-2011-winners.py

	@echo 'WB 2011 Winner Expenses'
	@python3 west-bengal-2011-winner-expenses.py

	@echo 'WB 2011 Constituency Page'
	@node west-bengal-2011-constituency-page-specific.js
	@python3 west-bengal-2011-constituency-page-specific.py

# 2016 split
constituency-2016:
	@echo 'WB 2016 Constituency'
	@python3 west-bengal-2016-assembly.py

winners-2016:
	@echo 'WB 2016 Winners'
	@python3 west-bengal-2016-winners.py

winner-expenses-2016:
	@echo 'WB 2016 Winner Expenses'
	@python3 west-bengal-2016-winner-expenses.py

constituency-specific-2016:
	@echo 'WB 2016 Constituency Page'
	@node west-bengal-2016-constituency-page-specific.js
	@python3 west-bengal-2016-constituency-page-specific.py

# 2011 split
constituency-2011:
	@echo 'WB 2011 Constituency'
	@python3 west-bengal-2011-assembly.py

winners-2011:
	@echo 'WB 2011 Winners'
	@python3 west-bengal-2011-winners.py

winner-expenses-2011:
	@echo 'WB 2011 Winner Expenses'
	@python3 west-bengal-2011-winner-expenses.py

constituency-specific-2011:
	@echo 'WB 2011 Constituency Page'
	@node west-bengal-2011-constituency-page-specific.js
	@python3 west-bengal-2011-constituency-page-specific.py