all:
	# WB 2016
	@echo 'WB 2014 Trends'
	@python3 west-bengal-2014-trends.py

	@echo 'WB 2014 Constituency-Wise Votes'
	@python3 west-bengal-2014-constituency-votes.py

	@node west-bengal-2014-constituency-page-specific.js
	@python3 west-bengal-2014-constituency-page-specific.py